//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP.CountriesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alpha3CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string subregionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string capitalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string alpha3Code {
            get {
                return this.alpha3CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.alpha3CodeField, value) != true)) {
                    this.alpha3CodeField = value;
                    this.RaisePropertyChanged("alpha3Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                if ((object.ReferenceEquals(this.regionField, value) != true)) {
                    this.regionField = value;
                    this.RaisePropertyChanged("region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subregion {
            get {
                return this.subregionField;
            }
            set {
                if ((object.ReferenceEquals(this.subregionField, value) != true)) {
                    this.subregionField = value;
                    this.RaisePropertyChanged("subregion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string capital {
            get {
                return this.capitalField;
            }
            set {
                if ((object.ReferenceEquals(this.capitalField, value) != true)) {
                    this.capitalField = value;
                    this.RaisePropertyChanged("capital");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CountriesService.CountriesSoap")]
    public interface CountriesSoap {
        
        // CODEGEN: Generating message contract since element name searchTerm from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        WEBAPP.CountriesService.GetCountriesResponse GetCountries(WEBAPP.CountriesService.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBAPP.CountriesService.GetCountriesResponse> GetCountriesAsync(WEBAPP.CountriesService.GetCountriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://tempuri.org/", Order=0)]
        public WEBAPP.CountriesService.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(WEBAPP.CountriesService.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string searchTerm;
        
        public GetCountriesRequestBody() {
        }
        
        public GetCountriesRequestBody(string searchTerm) {
            this.searchTerm = searchTerm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WEBAPP.CountriesService.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(WEBAPP.CountriesService.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WEBAPP.CountriesService.Country[] GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(WEBAPP.CountriesService.Country[] GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CountriesSoapChannel : WEBAPP.CountriesService.CountriesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountriesSoapClient : System.ServiceModel.ClientBase<WEBAPP.CountriesService.CountriesSoap>, WEBAPP.CountriesService.CountriesSoap {
        
        public CountriesSoapClient() {
        }
        
        public CountriesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountriesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountriesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEBAPP.CountriesService.GetCountriesResponse WEBAPP.CountriesService.CountriesSoap.GetCountries(WEBAPP.CountriesService.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public WEBAPP.CountriesService.Country[] GetCountries(string searchTerm) {
            WEBAPP.CountriesService.GetCountriesRequest inValue = new WEBAPP.CountriesService.GetCountriesRequest();
            inValue.Body = new WEBAPP.CountriesService.GetCountriesRequestBody();
            inValue.Body.searchTerm = searchTerm;
            WEBAPP.CountriesService.GetCountriesResponse retVal = ((WEBAPP.CountriesService.CountriesSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEBAPP.CountriesService.GetCountriesResponse> WEBAPP.CountriesService.CountriesSoap.GetCountriesAsync(WEBAPP.CountriesService.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEBAPP.CountriesService.GetCountriesResponse> GetCountriesAsync(string searchTerm) {
            WEBAPP.CountriesService.GetCountriesRequest inValue = new WEBAPP.CountriesService.GetCountriesRequest();
            inValue.Body = new WEBAPP.CountriesService.GetCountriesRequestBody();
            inValue.Body.searchTerm = searchTerm;
            return ((WEBAPP.CountriesService.CountriesSoap)(this)).GetCountriesAsync(inValue);
        }
    }
}
